name: restaurant_bukuku
description: "Test PT Bukuku Solusi Kreatif"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

#----------------- PACKAGES -----------------#

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.1
  intl: ^0.19.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.4
  rename: ^3.0.1
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^5.0.2
  open_street_map_search_and_pick: ^0.1.1
  lottie: ^3.1.2
  figma_layout_grid: ^0.3.2
  get_storage: ^2.1.1
  image_picker: ^1.0.7
  pinput: ^5.0.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.1.0

  # Firebase
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.1.6

  # Icons
  cupertino_icons: ^1.0.2
  iconsax_flutter: ^1.0.0

  # State Management
  get: ^4.6.6

#--------------- PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

#--------------- LOCAL ASSETS --------------#

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/animations/
    - assets/images/no_animations/
    - assets/images/background/
    - assets/logos/
    - assets/json/
    - assets/json/provinsi/
    - assets/json/kabupaten/
    - assets/json/kecamatan/

#--------------- LOCAL FONTS ---------------#

  fonts:
    - family: "Roboto"
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 800
