// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQMNWzsPxYITiykf0DMblLrAxbiPDtmI',
    appId: '1:968070639396:web:4893b69823c082a9014db1',
    messagingSenderId: '968070639396',
    projectId: 'restaurant-bukuku',
    authDomain: 'restaurant-bukuku.firebaseapp.com',
    storageBucket: 'restaurant-bukuku.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBftPG5tW4ZMSrfyfDLLvaQX9l8owz8iv4',
    appId: '1:968070639396:android:3459b9ae18bd4da4014db1',
    messagingSenderId: '968070639396',
    projectId: 'restaurant-bukuku',
    storageBucket: 'restaurant-bukuku.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAysbd62h9kwK75zLth7eXtpCmnCW9yf5g',
    appId: '1:968070639396:ios:f1ff18afa2ec68aa014db1',
    messagingSenderId: '968070639396',
    projectId: 'restaurant-bukuku',
    storageBucket: 'restaurant-bukuku.appspot.com',
    iosClientId: '968070639396-t0cijs0fj0bj1nput54jqo1jjv12bmkd.apps.googleusercontent.com',
    iosBundleId: 'id.bukuku.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB45_jeA19r307h0SyuYFFGB_XzcP1Bwzs',
    appId: '1:780249870739:ios:0039896c2dc1ff4b3f7866',
    messagingSenderId: '780249870739',
    projectId: 'in-foodmenu-multi-merchant',
    storageBucket: 'in-foodmenu-multi-merchant.appspot.com',
    androidClientId: '780249870739-2npu9onn2umi4ms929b6dpcaacpvhm50.apps.googleusercontent.com',
    iosClientId: '780249870739-qk21mhhcn442oggdd30g612so3tmril0.apps.googleusercontent.com',
    iosBundleId: 'com.example.inPosMultimerchant.RunnerTests',
  );
}